superset:
  image:
    repository: d41d8cd98f00b204e9800998e/quickview-superset
    tag: latest
    pullPolicy: Always

  replicas: 1

  metadata:
    namespace: superset

  auth:
    firstname: admin
    lastname: admin
    email: admin@mail.com

  service:
    type: NodePort
    host: localhost
    port: 8088
    targetPort: 8088
    nodePort: 32123

  integrations:

    redis:
      host: redis
      port: 6379
      db: 1
      url: redis://redis:6379/1

    clickhouse:
      externalName: clickhouse.clickhouse.svc.cluster.local
