apiVersion: v1
kind: Secret

metadata:
  name: {{ include "quickview.fullname" . }}
  labels:
    {{- include "quickview.labels" . | nindent 4 }}

data:
    wss_node_provider: {{ .Values.wssNodeProvider | b64enc }}
