apiVersion: v1
kind: Secret

metadata:
  name: {{ include "superset.fullname" . }}
  labels:
    {{- include "superset.labels" . | nindent 4 }}

data:
    secret_key: {{ .Values.secretKey | b64enc }}

    sqlalchemy_database_uri: {{ .Values.integrations.postgresql.sqlalchemyDatabaseUri | b64enc }}

    clickhouse_password: {{ .Values.integrations.clickhouse.password | b64enc }}

    superset_username: {{ .Values.auth.username | b64enc }}
    superset_password: {{ .Values.auth.password | b64enc }}
