bases:
- ../../environments.yaml

repositories:
  - name: bitnami
    url: registry-1.docker.io/bitnamicharts
    oci: true

helmDefaults:
  cleanupOnFail: true

releases:
  - name: kafka

    namespace: kafka
    createNamespace: true

    chart: bitnami/kafka
    version: 26.10.0

    values:
    - conf.d/values.yaml.gotmpl
